import = [
    "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

[window]
opacity=0.8
option_as_alt="OnlyLeft"

[font]

# Normal font style
normal = { family = "Ubuntu Mono derivative Powerline", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 11.25  # Default: 11.25es

# For tmux bindings
[[keyboard.bindings]]
key = "<"
mods = "Super|Shift"
chars = "\u001B<"

[[keyboard.bindings]]
key = ">"
mods = "Super|Shift"
chars = "\u001B>"

[[keyboard.bindings]]
key = "R"
mods = "Super|Shift"
chars = "\u001BR"

[[keyboard.bindings]]
key = "b"
mods = "Super"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "f"
mods = "Super"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "m"
mods = "Super"
chars = "\u001Bm"

[[keyboard.bindings]]
key = "r"
mods = "Super"
chars = "\u001Br"

[[keyboard.bindings]]
key = "v"
mods = "Super"
chars = "\u001Bv"

[[keyboard.bindings]]
key = "w"
mods = "Super"
chars = "\u001Bw"

[[keyboard.bindings]]
key = "x"
mods = "Super"
chars = "\u001Bx"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "="
mods = "Control|Shift"
action = "ResetFontSize"